### ISSUE TITLE
Doesn't want to switch back from double extension

### ISSUE THREAD

**Issue by Epskampie** [cdyson37/vscode-extensionswitcher#1]
Hi, great extension! Small problem though:

With these settings:

```
"extensionswitcher.extensions": [
        ".html.twig",
        ".scss",
        ".css",
        ".php",
        ".module.css",
        ".module.scss",
        ".tsx",
        ".ts",
        ".js",
        ".jsx",
    ],
```

it doesn't want to switch back from `foobar.module.scss` to `foobar.tsx`

**Comment by Epskampie** [comment]
I switched to https://marketplace.visualstudio.com/items?itemName=JohannesRudolph.file-ext-switcher which doesn't have this bug.

**Comment by cdyson37** [comment]
Sorry! I would love to fix this but crazy busy at the moment.

**Comment by Epskampie** [comment]
No worries, you gave this away for free, so you don't owe anybody any support on it!
